  name: Header
  
  on:
    workflow_dispatch:
   
      jobs:
        build:
          runs-on: ubuntu-latest
          
     uses: lowlighter/metrics@latest
   with:
     filename: metrics.classic.svg
     token: ${{ secrets.ALL_TOKEN }}
     base: header, repositories
     plugin_lines: yes
