name: Metrics badges

on:
  workflow_dispatch:

jobs:
  metric:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Example
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.ALL_TOKEN }}
          base: header, repositories
          plugin_lines: yes
